---
title: "Lecture 5 - Key"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
```


## Stratified Random Sampling
Suppose the population is partioned into disjoint sets of sampling units called __strata__. If a sample is selected within each stratum, then this sampling procedure is known as __stratified sampling.__
\vfill
If we can assume the strata are sampled independently across strata, then

1. *the estimator of $t$ or $\bar{y}_U$ can be found by combining stratum sample sums or means using appropriate weights*
\vfill
2. *the variances of the estimators associated with the individual strata can be summed to obtain the variance of an estimator associated with the whole population. (Given independence, the variance of a sum equals the sum of the individual variances.)*
\vfill

Point (2) implies that only within-stratum variances contribute ot the variance of an estimator. Thus, the basic motivating principle behind using stratification to produce an estimator with small variance is to partition the population so that units within each stratum are as similar as possible. *This is known as the __stratification principle.__*

\vfill
Recall the bird dataset used in Lab 3. Stratifying by terrain, or habitat type, greatly reduced the variance of the estimator.
\vfill
In general ecological studies, it is common to stratify a geographical region into subregions that are similar with respect to a known variable such as elevation, animal habitat type, vegetation type, ect... because it is suspected that the $y$-values may very greatly across strata while they will tend to be similar within each stratum. Analogously, when sampling people, it is common to stratify on variables such as gender, age groups, income levels, education levels, marital status, ect.
\vfill

Sometimes strata are formed based on sampling convenience. For example, suppose a large study region appears to be homogenous (that is, there are no spatial patterns) and is stratified based on the geographical proximity of the sampling units. Taking a stratified sample ensures the sample is spread throughout the study region. *It may not, however, lead to any significant reduction in the variance of an estimator.*
\vfill

If the $y$-values are spatially correlated ($y$-values tend to be similar for neighboring units), geographically determined strata can improve estimation of population parameters.
\vfill

\newpage

\subsection*{Stratified Sampling Notation}
\begin{eqnarray*}
	H &=& \text{ the number of strata}\\
	N_h &=& \text{ number of population units in stratum $h$, where $h=1,2,\dots, H$}\\
	N &=& \sum_{h=1}^H N_h= \text{ the number of units in the population}\\
	n_h &=& \text{ number of sampled units in stratum $h$}\\
	n &=& \sum_{h=1}^H n_h = \text{ the total number of units sampled} \\
	y_{hj} &=& \text{ the $y$-value associated with unit $j$ in stratum $h$} \\
	\bar{y}_h &=& \text{ the sample mean for stratum $h$}\\
	t_h &=& \sum_{j=1}^{N_h} y_{hj} = \text{ the stratum $h$ total}\\
	t&=& \sum_{h=1}^H \sum_{j=1}^{N_h} y_{hj} = \sum_{h=1}^H t_h = \text{ the population total}\\
	\bar{y}_{hU} &=& \frac{t_h}{N_h} = \text{ stratum $h$ mean} \\
\bar{y}_U &=& \frac{1}{N}\sum_{h=1}^H \sum_{j=1}^{N_h} y_{hj} = \frac{t}{N} = \text{ the population mean}	
\end{eqnarray*}
\vfill
If a simple random sample is taken within each stratum, then the sampling design is called stratified simple random sampling.
\vfill
For stratum $h$, there are $\binom{N_h}{n_h}$ possible SRSs of size $n_h$. Therefore, there are $\binom{N_1}{n_1}\binom{N_2}{n_2} \dots \binom{N_H}{n_H}$ possible stratified SRSs for specified stratum sample sizes $n_1, \dots, n_H$.
\vfill
If $\mathcal{S}_{strat}$ is a stratified SRS, then the probability of selecting $\mathcal{S}_{strat}$ is
	\begin{equation*}
	P(\mathcal{S}_{strat}) = \prod_{h=1}^H \frac{1}{\binom{N_h}{n_h}} = \frac{1}{\binom{N_1}{n_1} \dots \binom{N_H}{n_H} }
	\end{equation*}
	\vfill
*Thus, every possible stratified SRS having the sample sizes $n_1, \dots, n_H$ has the same probability of being selected.*

\newpage
#### Estimation of $\bar{y}_U$ and $t$
Because a SRS was taken within each stratum, we can apply the estimator formulas for simple random sampling to each stratum. We can estimate each stratum population mean $\bar{y}_{hU}$ and each stratum population total $t_h$. 
\vfill
The formulas are:
	\begin{eqnarray*}
	\hat{\bar{y}}_{hU} &=& \hat{p}_h = \bar{y}_h = *\frac{1}{n_h}\sum_{j=1}^{n_h} y_{hj}* \\
	\hat{t}_h &=& N_h \bar{y}_h = *\frac{N_h}{n_h} \sum_{j=1}^{n_h} y_{hj}*
	\end{eqnarray*}
\vfill
Example 1. Considered a smaller version of the bird dataset with only two strata: prairie (stratum 1) and non-prairie (stratum 2). Let $N_1 = 40$, $N_2 = 40,$ $n_1 = 4$ and $n_2=4$. Then let $\{y_{11}, ...,y_{14}\} = \{7,4,9,10\}$ and $\{y_{21}, ...,y_{24}\} = \{9,12,12,11\}$
\vfill
Compute:

$\bar{y}_1 = *\frac{30}{4} = 7.5*$
\vfill
$\hat{t}_1 = \frac{40}{4} \times 30 = 300$
\vfill
$\bar{y}_2 =\frac{44}{4} = 11$
  \vfill
$\hat{t}_2 = \frac{40}{4} \times 44 = 440$
\vfill

Because each $\hat{t}_h$ is an unbiased estimator of the stratum total $t_h$ for $i=1,2,\dots,k$ their sum will be an unbiased estimator for the population total $t$. That is $\hat{t}_{str} = \sum_h \hat{t}_h$ is an unbiased estimator of $t$.
\vfill
An unbiased estimator of $\bar{y}_U$ is a weighted average of the stratum sample means
	\begin{equation*}
	\hat{\bar{y}}_{U,str} = \frac{\hat{t}_{str}}{N}=\frac{1}{N} \sum_{h=1}^H N_h \bar{y}_h
	\end{equation*}
\vfill
Now compute the population total and population mean
\vfill

*$\hat{t}_{str} = t_1 + t_2 = 300 + 440 = 740$*
\vfill
*$\hat{\bar{y}}_{U,str} = \frac{40}{80}\bar{y}_1 + \frac{40}{80}\bar{y}_2 = 9.25$*
  \vfill


Before studying the overall variances $V(\hat{t}_{str})$ and $V(\hat{\bar{y}}_{U,str})$, we need to look at the within-stratum variances.
\vfill
\newpage

Because a SRS is taken within each stratum $h$, we can apply the results for simple random sampling estimators to each stratum. The variances of the stratified SRS estimators of the mean and total are:
	\begin{equation*}
	V(\hat{\bar{y}}_{Uh})= \left( 1- \frac{n_h}{N_h} \right) \frac{S_h^2}{n_h} \hspace{3cm} V(\hat{t}_h)=N_h(N_h-n_h) \frac{S_h^2}{n_h}
	\end{equation*}
	where $S_h^2$ is the variance for stratum $h$.
\vfill
Because the simple random samples are \emph{independent} across the strata, the variance of $\hat{t}_{str}$ is the sum of the individual stratum variances:
	\begin{equation*}
	*V(\hat{t}_{str}) = \sum_{h=1}^H V(\hat{t}_h)= \sum_{h=1}^H N_h(N_h-n_h) \frac{S_h^2}{n_h}*
	\end{equation*}
\vfill	
Dividing by $N^2$ gives $V(\hat{\bar{y}}_{U,str})$:
	\begin{equation*}
		V(\hat{\bar{y}}_{U,str}) = \left(\frac{1}{N^2}\right) V(\hat{t}_{str}) = \left(\frac{1}{N^2}\right)  \sum_{h=1}^H N_h(N_h-n_h) \frac{S_h^2}{n_h}
	\end{equation*}
\vfill
Again in most cases, $S_h^2$ is unknown, so we use $s_h^2$ to get an unbiased estimator of $V(\hat{t}_h)$, where $s_h^2$ is the sample variance of the $n_h$ $y$-values sampled from stratum $h$. Using $s_h^2$ in place of $S_h^2$ above returns $\hat{V}(\hat{t}_{str})$ and $\hat{V}(\hat{\bar{y}}_{U,str}).$ 
\vfill
Taking a square root of  $\hat{V}(\hat{t}_{str})$ or $\hat{V}(\hat{\bar{y}}_{U,str})$ yield the corresponding standard error, which is used in generating confidence intervals. 
\vfill
Suppose the sample variances of strata 1 and strata 2 are $s_1^2$ = `r var(c(7,4,9,10))` and $s_2^2$ = `r var(c(9,12,12,11))`, compute the variance of $\hat{t}_1$, $\hat{t}_2$, and $\hat{t}_{str}$.
\vfill
*$V(\hat{t}_1) = 40\times (40 - 4)  \frac{7}{4} = 2520$*
\vfill
*$V(\hat{t}_2) = 40\times (40 - 4)  \frac{2}{4} = 720$*
\vfill
*$V(\hat{t}_{str}) = V(\hat{t}_1) + V(\hat{t}_2) = 3240$*
\vfill

\newpage

#### Confidence intervals for $\bar{y}_U$ and $t$
If all of the stratum sample sizes $n_h$ are sufficiently large ($\approx n_h \geq 30)$ an approximate 100(1-$\alpha$)\% confidence interval for $\bar{y}_U$ and $t$ are 
	\begin{equation*}
	\hat{\bar{y}}_{U,str} \pm z^*\sqrt{\hat{V}(\hat{\bar{y}}_{U,str}}) \hspace{3cm} \hat{t}_{str} \pm z^*\sqrt{\hat{V}(\hat{t}_{str}})
	\end{equation*}
	where $z^*$ is the upper $\alpha/2$ critical value from the standard normal distribution.
\vfill	
For smaller sample sizes, the following confidence intervals are recommended:
	\begin{equation*}
	\hat{\bar{y}}_{U,str} \pm t^*\sqrt{\hat{V}(\hat{\bar{y}}_{U,str}}) \hspace{3cm} \hat{t}_{str} \pm t^*\sqrt{\hat{V}(\hat{t}_{str}})
	\end{equation*}	
	where $t^*$ is the upper $\alpha/2$ critical value form the $t(d)$ distribution. In this case, $d$ is Satterthwaite's approximation of degrees of freedom $d$ where
	\begin{equation*}
	d = \frac{\left(\sum_{h=1}^H a_h s_h^2\right)^2}{\sum_{h=1}^H(a_h s_h^2)^2/(n_h - 1)} = \frac{(\hat{V}(\hat{t}_{str}))^2}{\sum_{h=1}^H(a_h s_h^2)^2/(n_h - 1)}
	\end{equation*}
	where $a_h = N_h (N_h - n_h)/n_h.$
\vfill	
If the stratum sizes $n_h$ are all equal and the stratum size $N_h$ are all equal, then the degrees of freedom reduces to $d=n-H$ where $n=\sum n_h$ is the total sample size. Some packages (including R) will use $n-H$ degrees of freedom as the default.
\vfill
One-sided confidence intervals can be generated in the same fashion as before.

\newpage
#### Efficiency of Stratified Simple Random Sampling
Because the variance formulas for $\hat{t}_{str}$ and $\hat{\bar{y}}_{U,str}$ are determined only from within-stratum variances, the precision of the estimators can be improved by forming strata with small $S_h^2$ values (strata with similar $y-values$ within each stratum). *To contrast stratified random sampling with SRS we will compare $\hat{V}(\hat{\bar{y}}_U)$ from a SRS to $\hat{V}(\hat{\bar{y}}_{str})$ from a stratified SRS.*
\vfill
If the variance of the stratified sampling estimator is less than the variance of the SRS estimator,
*then we say that $\hat{\bar{y}}_{U,str}$ __is more efficient__ than $\hat{\bar{y}}_U$.*
\vfill
A stratified SRS estimator will be more efficient than the SRS estimator of $\bar{y}_U$ or $t$ *if the variability between stratum means is sufficiently large relative to the within-stratum variability.* 
\vfill


##### Allocation of Sampling Units
Given that we have enough resources to allocate $n$ units among the $H$ strata, how do we determine the stratum sample sizes $n_h$?
\vfill
__Situation 1:__ If all of the strata are the same size and no prior information is available about the population, a reasonable choice would be *to assign equal (or nearly equal) sample sizes to the strata. That is, $n_h \approx \frac{n}{H}$.*
\vfill

Example: *Think about the bike use data from Lab. If we were concerned with bike use by different quadrants in Washington, D.C., equal sample sizes might be a reasonable choice.*
\vfill
\newpage

__Situation 2:__ If the strata are not all the same size and no prior information is available about the population, a reasonable choice would be to assign sample sizes *proportional to the sizes of the strata relative to the population size $N$. That is, $n_h \approx n\frac{N_h}{N}$ This is known as proportional allocation.*
\vfill

Example: Think about the example in Lab 3. Proportional allocation was used by many groups in this scenario.
\vfill

__Situation 3:__ The allocation scheme that minimizes $V(\hat{t}_{str})$ is called __optimum allocation__ and requires $$n_h = \frac{N_h S_h}{\sum_{l=1}^H N_l S_l} n$$.

Because the $S_h$ values are unknown, we would need prior point estimates to attempt optimum allocation.
\vfill

Example: Suppose I gave you the variance terms for the habitat types in the bird survey dataset. Then you would allocate those proportional to the product of the population size and the population standard deviation for each terrain.

\vfill
__Situation 4:__ In some cases, if the cost of sampling units varies from stratum to stratum, then the total cost of taking a stratified SRS may determine how to allocate units to strata.
\vfill
*We will talk more about this later.*	

\newpage



#### Quota Sampling
When the population is stratified based on more than one factor we are using __multifactor stratification.__ *Typically a sample is taken with every combination of strata across the factors.*
\vfill

A marketing survey was conducted to get information on computer users' use of the internet for shopping. The surveyor suspected there may be differences based on gender (2 levels), househould income (6 levels), and age (5 levels). T*here would be a $2\times 6 \times 5 = 60$ multifactor strata to sample from.*
\vfill

__Quota sampling__ is a form of stratified sampling and typically uses multifactor stratification. Taking a quota sample ensures that data are collected across the population with the belief that doing so will provide a representative sample from the population. *It also allows the researchers to generate estimates related to various subgroups.*
\vfill

So how does quota sampling differ from stratified simple random sampling? *In quota sampling, __the within stratum samples may not be random.__ Often some element of subjectivity enters into the sampling procedure.*
\vfill
A typical quota sample is based on:

1. Defining *the multifactor strata.*
\vfill
2. Determining the stratum sample sizes based on proportional allocation. These are also referred to as the __stratum quotas__. These sample sizes are based on either known or approximate stratum sizes. They can also be based on either known or approximate population proportions associated with each stratum.
\vfill
3. Data is collected by *predetermined data collection techniques( e.g., phone surveys, mail surveys, personal interviews, ect.) until the stratum quotas are satisfied (that is, until the desired number of responses are collected for each stratum.)*
\vfill

Although taking a quota sample can save a lot of time and money when compared to simple random sampling, the reseacher must realize that if quota sampling is used, *we cannot be sure that the selection of sampling units would be similar to units collected via simple random sampling.*
\vfill

Example. Consider online political polling. In principle, use of the estimation formulas based on random sampling techniques on data from a quota sample violates underlying assumptions. Therefore, we cannot be as confident in the results from quota sampling in comparison to results when a probability sampling method is used.
\vfill
\newpage

A student organization wants to determine if students favor extending the evening hours that the library remains open. They decided to take a quota sample based on strata related to class standing(first year, sophomore, junior, senior, graduate students). After deciding on the 5 quotas of 25 students for each of the 5 strata, data was collected at the library on consecutive evenings until all 5 quotas were satisfied. What concerns do you have?

\vfill
*You are sampling students who are known to study in the library and not sampling any students who are less likely to study in the library. Therefore, the recorded responses will be biased in support of extending the evening hours that the library remains open.*

\vfill
*Nonetheless, quota sampling has proven useful if the quotas are designed properly with careful attention paid to when, how, and where the data are collected.*

##### Poststratification
In some stratified sampling situations, we may not be able to determine from which stratum an observation belongs until it is actually observed.
\vfill
For example, a fish population may be stratified by age class, body length, body weight, or sex. A random sample of fish is collected. Then each sampled fish is examined and its stratum is recorded along with the response of interest. *Therefore, because the stratum for each fish is determined after sampling, it is not possible to guarantee exact stratum sample sizes $n_h$ for each age group, ect...*
\vfill
In many studies a simple random sample is taken from the population and then is stratified. *The procedure is known as __poststratification__ or __post-hoc stratification__.*
\vfill
In constrast to traditional stratified simple random sampling, *the stratum sample sizes $n_1, n_2, \dots, n_h$ are random variables.*
\vfill